config/routes.rb
Rails.application.routes.draw do
  get 'labels/:name', to: 'book_marks#tag', as: :label
  resources :book_marks
  resources :labels

  root 'book_marks#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/book_mark.rb
class BookMark < ActiveRecord::Base
acts_as_xlsx
 attr_accessor :label
	has_many :book_mark_labels, :dependent => :destroy
	has_many :labels, through: :book_mark_labels
  belongs_to :user

 


  def self.search(search)
  where("name LIKE ?", "%#{search}%")
  end



  def self.delete(labels)
      labels.each do |label|
   if label.book_marks.count == 1
     label.destroy
   end
  end
end

#def as_xls(options = {})
  #{
     # "Name" => name,
     # "Location" => url,
    #  "Label" => label,
   #   "Notes" => note,
  #    "Relesed" => created_at
 # }
#end
      

 
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |book_mark|
        csv << book_mark.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/book_mark_label.rb
class BookMarkLabel < ActiveRecord::Base
  belongs_to :label
  belongs_to :book_mark
  belongs_to :user

 # before_destroy :delete_label

 # def delete_label
  #	self.label.delete
 # end
end

app/models/label.rb
class Label < ActiveRecord::Base
	attr_accessor :user
	has_many :book_mark_labels, :dependent => :destroy
	has_many :book_marks, through: :book_mark_labels
    belongs_to :user


    def self.labled(name)
    	find(name).book_marks
   	end
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :label
	 has_secure_password
	 has_many :book_marks
	 #has_many :book_mark_labels
	 has_many :labels
	 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/book_marks_controller.rb
class BookMarksController < ApplicationController
  before_filter :authorize
  before_action :set_book_mark, only: [:show, :edit, :update, :destroy]
  
   #helper_method :sort_column, :sort_direction
  # GET /book_marks
  # GET /book_marks.json
  def index
      #@book_marks = current_user.book_marks.all
       if params[:search]
        @book_marks = current_user.book_marks.search(params[:search])
      else
        @book_marks = current_user.book_marks.all
      end
      @labels = current_user.labels.all
      #@book_marks = BookMark.order(params[:sort])
     # @book_marks = BookMark.order(:name)
    respond_to do |format|
      format.html
      format.csv { render text: @book_marks.to_csv }
      format.xlsx 
    end
  end

  # GET /book_marks/1
  # GET /book_marks/1.json
  def show
    @book_mark = BookMark.find(params[:id])
  end


  def tag
    if params[:name]
      @book_marks = Label.labled(params[:name])
    else
      @book_marks = current_user.book_marks.all
    end
end
  


  # GET /book_marks/new
  def new
    @book_mark = BookMark.new
  end

  # GET /book_marks/1/edit
  def edit
    @book_mark = BookMark.find(params[:id])
  end

  # POST /book_marks
  # POST /book_marks.json
  def create
    b = book_mark_params
   # b.delete(:label_id)
    @book_mark = BookMark.create(b.merge(user_id: current_user.id))
    params[:book_mark][:label].split(',').each do |label|
     l = Label.where(:name => label, user_id: current_user.id).first_or_create
   BookMarkLabel.create(:label_id => l.id, :book_mark_id => @book_mark.id)
    end
    respond_to do |format|
   if @book_mark.save
      format.html { redirect_to @book_mark, notice: 'book mark created successfully' }
    else
      format.html { render :new}
    end
  end
end
    #params[:book_mark][:label].split(',').each do |label|
     # Label.where(:name => label).first_or_create
      #b = BookMarkLabel.create(:label_id => @label, :book_mark_id => @book_mark)
     #render :action => :index
    #end
 #end
   # PATCH/PUT /book_marks/1
  # PATCH/PUT /book_marks/1.json
  def update
    respond_to do |format|
      if @book_mark.update(book_mark_params)
        format.html { redirect_to @book_mark, notice: 'Book mark was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_mark }
      else
        format.html { render :edit }
        format.json { render json: @book_mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_marks/1
  # DELETE /book_marks/1.json
  def destroy
    labels = @book_mark.labels
    BookMark.delete(labels)
    @book_mark.destroy
    respond_to do |format|
      format.html { redirect_to book_marks_url, notice: 'Book mark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_mark
      @book_mark = BookMark.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def book_mark_params
      params.require(:book_mark).permit(:name, :url, :label, :note, :user_id)
    end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_filter :authorize
  before_action :set_label, only: [:show, :edit, :update, :destroy]

def index
  @labels = current_user.labels.all
end

def show
  @label = current_user.labels.all
end


def edit
    @label = Label.find(params[:id])
  end

def update
    
     @label.update(label_params)
     redirect_to labels_path
       
  end

  # DELETE /book_marks/1
  # DELETE /book_marks/1.json
  def destroy
    @label.destroy
    redirect_to labels_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end
   

    # Never trust parameters from the scary internet, only allow the white list through.
    def label_params
      params.require(:label).permit(:name)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  end

  def create
  user = User.find_by_email(params[:email])
    
    if user && user.authenticate(params[:password])
      
      session[:user_id] = user.id
      redirect_to '/'
    else
    
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'

end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
    end

    def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end	

app/helpers/book_marks_helper.rb
module BookMarksHelper
	#def label_cloud(labels)#, classes)
    #max = labels.collect(&:count)
   # labels.each do |label|
    	#index = label.count.to_i
      #index = label.count.to_f / max.count * (classes.size - 1)
     #yield(label)#, classes[index.round])
   #end
  #end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_marks/edit.html.erb
<html>
<head>
<style>
header {
    background-color:teal;
    color:white;
    text-align:center;
    padding:5px;
}
nav {
    line-height:30px;
    background-color:#eeeeee;
    height:400px;
    width:150px;
    float:left;
    padding:5px;        
}
section {
    width:350px;
    float:left;
    padding:10px;    
}
footer {
    background-color:teal;
    color:white;
    clear:both;
    text-align:center;
    padding:5px;     
}
table#t01 th  {
    background-color: black;
    color: white;
}
</style>
</head>
    <header>
        <h1><center>EDIT BOOKMARK</center></h1>
        <center><%= form_tag(book_marks_path, :method => 'get') do %>
             <%= text_field_tag :search, params[:search] %><br>
                    <%= submit_tag "Search" %>
               <% end %> 
       
          </center>

          
      </header>
<nav>
<%= link_to "Bookmark", root_path %></br>
<%= link_to "Add Bookmark", new_book_mark_path %></br>
Exporting bookmarks:
  <%= link_to "CSV", book_marks_path(format: "csv") %> |
  <%= link_to "Excel", book_marks_path(format: "xlsx") %><br>
  <%= link_to "Manage label", labels_path %>

</nav>
<section>
<%= form_for(@book_mark) do |f| %>
  <div class="field">
    <b><%= f.label :Name %></b>:<%= f.text_field :name %>
  </div>
  <br>


  <div class="field">
    <b><%= f.label :Location %></b>: <%= f.text_field :url %>
  </div>
  <br>
  
    <div class="area">
   <b> <%= f.label :Notes %></b>:<%= f.text_area :note %>   
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  <%= link_to 'Show', @book_mark %> |
<%= link_to 'Back', book_marks_path %>
  <% end %>
</section>
<footer>
Copyright © Bookmark.com
</footer>
</body>
</html>

app/views/book_marks/index.html.erb
<html>
<head>
<style>
header {
    background-color:teal;
    color:white;
    text-align:center;
    padding:5px;
}
nav {
    line-height:30px;
    background-color:#eeeeee;
    height:400px;
    width:150px;
    float:left;
    padding:5px;        
}
section {
    width:350px;
    float:left;
    padding:10px;    
}
footer {
    background-color:teal;
    color:white;
    clear:both;
    text-align:center;
    padding:5px;     
}
table#t01 th  {
    background-color: black;
    color: white;
}


</style>
</head>
    <header>
        <h1><center>BOOKMARK PAGE</center></h1>
            <center><%= form_tag(book_marks_path, :method => 'get') do %>
        <%= text_field_tag :search, params[:search] %>
                    <%= submit_tag "Search" %>
                    
               <% end %>
            </center>          
      </header>    
      <nav>
      
 

<%= link_to "Bookmark", root_path %></br>

<div style="width:100px; height:200px; overflow: auto;" >
<ul style="list-style-type:circle">
<% @labels.each do |label| %>
<li><%= link_to label.name,label %>
(<%= label.book_mark_labels.count %>)</li>
  <% end %>
</div>
</ul>

</div>
<%= link_to "Add Bookmark", new_book_mark_path %></br>
Exporting bookmarks:
  <%= link_to "CSV", book_marks_path(format: "csv") %> |
  <%= link_to "Excel", book_marks_path(format: "xlsx") %><br>
<%= link_to "Manage label", labels_path %>
</nav>
<section>

<table id="t01", align="center">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Label</th>
      <th>Notes</th>
      <th>Relesed</th>
      <th colspan="20"></th>
    </tr>
  </thead>


  <tbody>
    <% @book_marks.each do |book_mark| %>
      <tr>
        <td><%=link_to book_mark.name, "http://#{book_mark.url}", target: "_blank" %></td>
        <td><%= book_mark.url %></td>
        <td><%= raw book_mark.labels.map(&:name).join(', ') %></td>
        <td><%= book_mark.note %></td>
        <td><%= book_mark.created_at.strftime("%B %d") %></td>
        <td><%= link_to 'Show', book_mark %></td>
        <td><%= link_to 'Edit', edit_book_mark_path(book_mark) %></td>
        <td><%= button_to 'Destroy', book_mark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</section>
<footer>
Copyright © Bookmark.com
</footer>
</body>
</html>

app/views/book_marks/new.html.erb
<html>
<head>
<style>

header {
    background-color:teal;
    color:white;
    text-align:center;
    padding:5px;
}

nav {
    line-height:30px;
    background-color:#eeeeee;
    height:400px;
    width:150px;
    float:left;
    padding:5px;        
}
section {
    width:350px;
    float:left;
    padding:10px;    
}
footer {
    background-color:teal;
    color:white;
    clear:both;
    text-align:center;
    padding:5px;     
}
</style>
</head>
<header>
<h1><center>NEW BOOKMARK</center></h1>
<center><%= form_tag(book_marks_path, :method => 'get') do %>
             <%= text_field_tag :search, params[:search] %><br>
                    <%= submit_tag "Search" %>
               <% end %>
            </center>
</header>
<nav>
<%= link_to "Bookmark", root_path %></br>
<%= link_to "Add Bookmark", new_book_mark_path %></br>
Exporting bookmarks:
  <%= link_to "CSV", book_marks_path(format: "csv") %> |
  <%= link_to "Excel", book_marks_path(format: "xlsx") %><br>
  <%= link_to "Manage label", labels_path %>

</nav>
<section>
<center>
<%= form_for(@book_mark) do |f| %>
  <div class="field">
   <pre> <b><%= f.label :Name %></b>     : <%= f.text_field :name %></Pre>
  </div>
  <br>


  <div class="field">
   <pre> <b><%= f.label :Location %></b> : <%= f.text_field :url %></pre>
  </div>
  <br>

  <div class="field">
  <pre> <b> <%= f.label :Labels %></b> :  <%= f.text_field :label %></pre>
  </div>
  <br>

  <div class="area">
  <pre> <b> <%= f.label :Notes %></b>  :  <%= f.text_area :note %> </pre>
  </div>

  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  </ceneter>
  <%= link_to 'Back', book_marks_path %>
<% end %>
</section>
<footer>
Copyright © Bookmark.com
</footer>
</body>
</html>

app/views/book_marks/show.html.erb
<p id="notice"><%= notice %></p>
<h1> SHOW BOOKMARK</h1>

<p>
  <strong>Name:</strong>
  <%= @book_mark.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @book_mark.url %>
</p>

<p>
  <strong>Label:</strong>
  <%= @book_mark.labels.map(&:name).join(', ') %>
</p>

<p>
  <strong>Note:</strong>
  <%= @book_mark.note %>
</p>

<%= link_to 'Edit', edit_book_mark_path(@book_mark) %> |
<%= link_to 'Back', book_marks_path %>

app/views/book_marks/tag.html.erb


<h1>BOOKMARK</h1>
  <table align="center">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Label</th>
      <th>Notes</th>
      <th>Relesed</th>
      <th colspan="20"></th>
    </tr>
  </thead>


  <tbody>
    <% @book_marks.each do |book_mark| %>
      <tr>
        <td><%=link_to book_mark.name, "http://#{book_mark.url}", target: "_blank" %></td>
        <td><%= book_mark.url %></td>
        <td><%= raw book_mark.labels.map(&:name).join(', ') %></td>
        <td><%= book_mark.note %></td>
        <td><%= book_mark.created_at.strftime("%B %d") %></td>
        <td><%= link_to 'Show', book_mark %></td>
        <td><%= link_to 'Edit', edit_book_mark_path(book_mark) %></td>
        <td><%= button_to 'Destroy', book_mark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/labels/edit.html.erb
<h1> Edit Label</h1>


<%= form_for(@label) do |f| %>
  <div class="field">
    <b><%= f.label :Name %></b>:<%= f.text_field :name %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<%= link_to 'Back', labels_path %>
  <% end %>

app/views/labels/index.html.erb
<html>
<head>
<style>
header {
    background-color:teal;
    color:white;
    text-align:center;
    padding:5px;
}
nav {
    line-height:30px;
    background-color:#eeeeee;
    height:400px;
    width:150px;
    float:left;
    padding:5px;        
}
section {
    width:350px;
    float:left;
    padding:10px;    
}
footer {
    background-color:teal;
    color:white;
    clear:both;
    text-align:center;
    padding:5px;     
}
table#t01 th  {
    background-color: black;
    color: white;
}
</style>
</head>
    <header>
        <h1><center>BOOKMARK PAGE</center></h1>
            <center><%= form_tag(book_marks_path, :method => 'get') do %>
             <%= text_field_tag :search, params[:search] %><br>
                    <%= submit_tag "Search" %>
               <% end %>
            </center>          
      </header>
      <div align="right">
          <%= link_to "SortByTitle", :sort => "name" %>|
          <%#= link_to "SortByLabel", :sort => "label.name" %>|
          <%#= link_to "SortByDate", :sort => "created_at" %>
      </div>    
      <nav>
      
 

<%= link_to "Bookmark", root_path %></br>

<div style="width:100px; height:200px; overflow: auto;" >
<ul style="list-style-type:circle">
<% @labels.each do |label| %>
<li><%= link_to label.name,label %>
<%= label.book_mark_labels.count %></li>
  <% end %>
</div>
</ul>

</div>
<%= link_to "Add Bookmark", new_book_mark_path %></br>
Exporting bookmarks:
  <%= link_to "CSV", book_marks_path(format: "csv") %> |
  <%= link_to "Excel", book_marks_path(format: "xlsx") %><br>
<%= link_to "Manage label", labels_path %>
</nav>
<section>

<table  align="center">
  <thead>
    <tr>
      <th><strong> Manage bookmark labels </strong></th>
       <th colspan="20"></th>
    </tr>
  </thead>
   <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td style="padding-right: 40px"><%= label.name %></td>
        <td style="padding-right: 10px"><%= link_to 'Rename', edit_label_path(label) %></td>
        <td style="padding-right: 10px"><%= button_to 'Remove', label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</section>
<footer>
Copyright © Bookmark.com
</footer>
</body>
</html>























app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmark</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %> 
  <h3 align="right"><%= link_to "Logout", '/logout' %></h3>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb

<!DOCTYPE html>
<html>
<head>
<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<meta charset="UTF-8">

<title>Elegant Login - Designscrazed</title>
<style>
body {
    background: url('http://i.imgur.com/Eor57Ae.jpg') no-repeat fixed center center;
    background-size: cover;
    font-family: Montserrat;
}



.login-block {
    width: 320px;
    padding: 20px;
    background: #fff;
    border-radius: 5px;
    border-top: 5px solid #ff656c;
    margin: 0 auto;
}

.login-block h1 {
    text-align: center;
    color: #000;
    font-size: 18px;
    text-transform: uppercase;
    margin-top: 0;
    margin-bottom: 20px;
}

.login-block input {
    width: 100%;
    height: 42px;
    box-sizing: border-box;
    border-radius: 5px;
    border: 1px solid #ccc;
    margin-bottom: 20px;
    font-size: 14px;
    font-family: Montserrat;
    padding: 0 20px 0 50px;
    outline: none;
}

.login-block input#username {
    background: #fff url('http://i.imgur.com/u0XmBmv.png') 20px top no-repeat;
    background-size: 16px 80px;
}

.login-block input#username:focus {
    background: #fff url('http://i.imgur.com/u0XmBmv.png') 20px bottom no-repeat;
    background-size: 16px 80px;
}

.login-block input#password {
    background: #fff url('http://i.imgur.com/Qf83FTt.png') 20px top no-repeat;
    background-size: 16px 80px;
}

.login-block input#password:focus {
    background: #fff url('http://i.imgur.com/Qf83FTt.png') 20px bottom no-repeat;
    background-size: 16px 80px;
}

.login-block input:active, .login-block input:focus {
    border: 1px solid #ff656c;
}

.login-block button {
    width: 100%;
    height: 40px;
    background: #ff656c;
    box-sizing: border-box;
    border-radius: 5px;
    border: 1px solid #e15960;
    color: #fff;
    font-weight: bold;
    text-transform: uppercase;
    font-size: 14px;
    font-family: Montserrat;
    outline: none;
    cursor: pointer;
}

.login-block button:hover {
    background: #ff7b81;
}

</style>
</head>

<body>
<div class="login-block">
    <h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>
 
  
 <p>
  <b>Name</b>: <%= f.text_field :name %><br>
</p>
<p>
  <b>Email</b>: <%= f.text_field :email %><br>
</p>
<p>  
  <b>Password</b>: <%= f.password_field :password %><br>
</p>
<p>  
  <b>Password Confirmation</b>: <%= f.password_field :password_confirmation %><br>
</p>  
  <%= f.submit "Submit" %>

<% end %>
</div>
</body>

</html>